services:
# 游릭 MLflow Server
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_SERVICE = http://mlflow:5000
    volumes:
      - ./mlruns:/mlflow/mlruns
    command:
      mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns --host 0.0.0.0 --port 5000

# 游릭 API FastAPI
  api:
    build:
      context: . 
      dockerfile: dockerfile
    container_name: UsedCarPrice
    ports:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
      - .env.docker
    volumes:
    - mlflow
    - prometheus

# 游릭 Prometheus
  prometheus:
  image: prom/prometheus:latest
  container_name: prometheus
  ports:
    - "9000:9000"
  volumes:
    - /prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  command:
    - --config.file=/etc/prometheus/prometheus.yml

# 游릭 Grafana
  grafana:
    image: grafana/graphana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data

networks:
  default:
    name: mlfast-net

